[alias]
x = "run -p xtask --"

xf = "run -p xtask -- format"
xc = "run -p xtask -- check"
xl = "run -p xtask -- clippy"
xt = "run -p xtask -- test"
xb = "run -p xtask -- build"
xr = "run -p xtask -- run"
xcs = "run -p xtask -- ci-smoke"
xh = "run -p xtask -- help"
xa = "run -p xtask -- format check clippy test build run"
